version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy-two:v1
  backend_user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user-two:v1
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed-two:v1
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend-two:v2a
