apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-user
  labels:
    app: udagram-api-user
spec:
  selector:
    matchLabels:
      app: udagram-api-user
  replicas: 1
  template:
    metadata:
      labels:
        app: udagram-api-user
    spec:
      containers:
      - name: udagram-api-user
        image: jacoba4/udagram-api-user-two:v1
        env:
          - name: POSTGRES_DB
            value: postgres
          - name: POSTGRES_USERNAME
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTGRES_HOST
            value: saljac.cy80cluefs3a.us-east-1.rds.amazonaws.com
          - name: AWS_BUCKET
            value: arn:aws:s3:::salyjacob
          - name: AWS_REGION
            value: us-east-1
          - name: AWS_PROFILE
            value: default
          - name: JWT_SECRET
            value: hello
          - name: URL
            value: http://localhost:8100
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m