apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  selector:
    matchLabels:
      app: backend-user
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
        - name: backend-user
          image: jacoba4/udagram-api-user
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: 250m
            limits:
              memory: "2048Mi"
              cpu: 1000m
          envFrom:
            - secretRef:
                name: env-secret
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: aws-secret
          ports:
            - containerPort: 8080 