apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  selector:
    matchLabels:
      app: backend-feed
  replicas: 2
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: jacoba4/udagram-api-feed
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: 1000m
            limits:
              memory: "4096Mi"
              cpu: 2000m
          envFrom:
            - secretRef:
                name: env-secret
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: aws-secret
          ports:
            - containerPort: 8080 