apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: jacoba4/udagram-frontend:v2a
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: 500m
            limits:
              memory: "2048Mi"
              cpu: 1000m
          envFrom:
            - secretRef:
                name: env-secret
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: aws-secret
          ports:
            - containerPort: 8080 