apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy
spec:
  selector:
    matchLabels:
      app: reverseproxy
  replicas: 1
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
        - name: reverseproxy
          image: jacoba4/reverseproxy
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: 500m
            limits:
              memory: "2048Mi"
              cpu: 1000m
          envFrom:
            - secretRef:
                name: env-secret
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: aws-secret
          ports:
            - containerPort: 8080 