name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to dockerhub
      env:
        USER: ${{secrets.DOCKERHUB_UNAME}}
        PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      run: docker login -u $USER -p $PASSWORD
    - name: Build the Docker image
      run: docker-compose -f docker-compose-build.yaml build --parallel
    - name: Tag and push images 
      env:
        USER: ${{secrets.DOCKERHUB_UNAME}}
      run: |
        docker image tag reverseproxy-two:v1 $USER/reverseproxy-two:v1
        docker push $USER/reverseproxy-two:v1
        docker image tag udagram-frontend-two:v2a $USER/udagram-frontend-two:v2a
        docker push $USER/udagram-frontend-two
        docker image tag udagram-api-user-two:v1 $USER/udagram-api-user-two:v1
        docker push $USER/udagram-api-user-two:v1
        docker image tag udagram-api-feed-two:v1 $USER/udagram-api-feed-two:v1
        docker push $USER/udagram-api-feed-two:v1