name: Docker user Image CI

on:
    push:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest

    
        steps:
        - name: Checkout 
          uses: actions/checkout@v2

        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_UNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./udagram-api-user
            file: ./udagram-api-user/Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_UNAME }}/udagram-api-user-two:v1
            cache-from: type=registry,ref=${{ secrets.DOCKERHUB_UNAME }}/udagram_api_user-two:buildcache
            cache-to: type=registry,ref=${{ secrets.DOCKERHUB_UNAME }}/udagram-api-user-two:buildcache,mode=max
